import NearMeIcon from '@mui/icons-material/NearMe';
import Head from 'next/head';
import Button from 'components/atoms/button';
import { RenderingArea } from 'components/organisms/RenderingArea';
import { SpriteSelectModeButton } from 'components/organisms/SpriteSelectModeButton';
import { Provider } from 'components/provider';
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Provider>
                    <Button variant={'primary'}>ボタン</Button>
                    <SpriteSelectModeButton>
                        <NearMeIcon />
                    </SpriteSelectModeButton>
                    <RenderingArea />
                </Provider>
            </>
        </>
    );
}
