import { Box, SvgIcon } from '@mui/material';
import Head from 'next/head';
import Icon from '../../public/favicon.svg';
import { FooterSection } from 'components/ecosystem/Footer';
import { RightBar } from 'components/ecosystem/RightBar';
import { RenderingSection } from 'components/ecosystem/RwnderView';
import { ThemeSection } from 'components/ecosystem/ThemeSection';
import { ToolBar } from 'components/ecosystem/ToolBar';
import { ToolMenues } from 'components/ecosystem/ToolConfMenues';
import { MenuSection } from 'components/ecosystem/TopMenus';
import Container from 'components/layout/Container';
import { Provider } from 'components/provider';
import { PortalProvider } from 'components/provider/Portal';
import { MQ } from 'mediaQuery';

export default function Home() {
    return (
        <>
            <Head>
                <title>craftia</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <>
                <Provider>
                    <Box
                        css={(theme) => ({
                            position: 'absolute',
                            top: 0,
                            zIndex: 1000,
                            width: '100vw',
                            backgroundColor: theme.colors.neutral200,
                        })}
                    >
                        <Container
                            css={{
                                justifyContent: 'space-between',
                                alignItems: 'flex-end',
                                width: '100%',
                                height: 46,
                                padding: '0px 20px',
                                gap: 15,
                            }}
                        >
                            <SvgIcon>
                                <Icon />
                            </SvgIcon>
                            <MenuSection css={{ alignItems: 'flex-end' }} />
                            <ThemeSection />
                        </Container>
                        <ToolMenues
                            css={{
                                height: 50,
                                zIndex: 1000,
                                padding: '0px 10px',
                                [MQ.md]: {
                                    padding: '0px 40px',
                                },
                            }}
                        />
                    </Box>
                    <ToolBar
                        css={{
                            position: 'absolute',
                            zIndex: 500,
                            top: 96,
                            width: 'auto',
                            height: 'calc(100% - 111px)',
                        }}
                    />
                    <PortalProvider />
                    <RenderingSection />
                    <Container
                        css={{
                            position: 'absolute',
                            zIndex: 500,
                            top: 96,
                            right: 0,
                            height: 'calc(100% - 111px)',
                        }}
                    >
                        <RightBar />
                    </Container>

                    <FooterSection
                        css={{
                            height: '15px',
                            position: 'absolute',
                            bottom: 0,
                            zIndex: 1000,
                        }}
                    />
                </Provider>
            </>
        </>
    );
}
