import Head from 'next/head';
import { LayerColumn } from 'components/organisms/LayerColumn';
import { LayerTreeRoot } from 'components/organisms/LayerTreeRoot';
import { Renderer } from 'components/organisms/Renderer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayerTreeRoot>
        <LayerColumn />
        <Renderer />
      </LayerTreeRoot>
    </>
  );
}
